In [1]:
import torch 

In [2]:
torch.cuda.is_available()

True

In [3]:
device = torch.device("cuda")

In [11]:
device 

device(type='cuda')

In [12]:
torch.__version__

'2.5.1'

In [13]:
!nvidia-smi

Tue Oct 28 11:26:29 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.99                 Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   42C    P8              4W /   30W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [14]:
#scalars

scalar = torch.tensor(7)
print(scalar)
print(scalar.item())
print(scalar.ndim)

tensor(7)
7
0


In [15]:
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [16]:
matrix = torch.tensor([[7, 8],
                      [9, 10]])

print(matrix.ndim)
print(matrix[1])
print(matrix.shape)
print(matrix[0: 1])

2
tensor([ 9, 10])
torch.Size([2, 2])
tensor([[7, 8]])


In [17]:
tensor = torch.tensor([[[7, 8, 9],
                        [3,4,5],
                       [10, 11, 13]]])


print(tensor.ndim)
print(tensor.shape)
print(tensor[0: 1])
print(tensor[0:-1])

3
torch.Size([1, 3, 3])
tensor([[[ 7,  8,  9],
         [ 3,  4,  5],
         [10, 11, 13]]])
tensor([], size=(0, 3, 3), dtype=torch.int64)


In [18]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[3.9826e-01, 3.2233e-01, 1.9548e-03, 7.1990e-01],
        [8.0028e-01, 2.5548e-01, 4.2895e-01, 5.7292e-04],
        [5.0782e-01, 3.3627e-01, 9.9574e-01, 8.3317e-01]])