In [2]:
import torch 

In [3]:
torch.cuda.is_available()

True

In [4]:
device = torch.device("cuda")

In [5]:
device 

device(type='cuda')

In [6]:
torch.__version__

'2.5.1'

In [7]:
!nvidia-smi

Thu Dec 25 16:24:40 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.99                 Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   43C    P0              4W /   45W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [8]:
#scalars

scalar = torch.tensor(7)
print(scalar)
print(scalar.item())
print(scalar.ndim)

tensor(7)
7
0


In [9]:
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [10]:
matrix = torch.tensor([[7, 8],
                      [9, 10]])

print(matrix.ndim)
print(matrix[1])
print(matrix.shape)
print(matrix[0: 1])

2
tensor([ 9, 10])
torch.Size([2, 2])
tensor([[7, 8]])


In [11]:
tensor = torch.tensor([[[7, 8, 9],
                        [3,4,5],
                       [10, 11, 13]]])


print(tensor.ndim)
print(tensor.shape)
print(tensor[0: 1])
print(tensor[0:-1])

3
torch.Size([1, 3, 3])
tensor([[[ 7,  8,  9],
         [ 3,  4,  5],
         [10, 11, 13]]])
tensor([], size=(0, 3, 3), dtype=torch.int64)


In [12]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9754, 0.3371, 0.3914, 0.8366],
        [0.7199, 0.8051, 0.3218, 0.7429],
        [0.5326, 0.0962, 0.6637, 0.5958]])

In [13]:
random_image_size_tensor = torch.rand(size=(244, 244, 3)) #height width color channel

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

In [14]:
#default data type is always float32
random_image_size_tensor.dtype

torch.float32

In [15]:
torch.arange(0,10)
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [16]:
torch.rand(1,3) #rows x columns

tensor([[0.7517, 0.2227, 0.3554]])

In [17]:
x = torch.arange(1,10).reshape(1, 3, 3)

x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [18]:
x[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [19]:
x[0][0]

tensor([1, 2, 3])

In [20]:
x[0][0][0]

tensor(1)

In [21]:
#getting all values of 0th and 1st dimension but only index of 1 of 2nd dimension

In [22]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [23]:
x[:, 1, 1]

tensor([5])

In [24]:
torch.rand(2,3,4,5)

tensor([[[[0.9666, 0.9431, 0.1839, 0.5634, 0.9008],
          [0.2623, 0.7012, 0.7526, 0.9244, 0.6540],
          [0.1537, 0.9621, 0.1310, 0.8101, 0.2607],
          [0.9760, 0.4421, 0.6935, 0.5972, 0.4295]],

         [[0.9657, 0.6646, 0.7581, 0.0043, 0.7574],
          [0.6724, 0.3696, 0.0906, 0.1401, 0.1339],
          [0.6091, 0.4338, 0.4822, 0.2398, 0.9161],
          [0.4346, 0.1826, 0.4404, 0.7795, 0.8622]],

         [[0.3575, 0.0024, 0.7226, 0.4521, 0.0178],
          [0.9111, 0.4480, 0.7649, 0.0506, 0.6225],
          [0.8718, 0.4296, 0.8581, 0.1687, 0.0898],
          [0.1794, 0.5479, 0.2507, 0.3228, 0.4636]]],


        [[[0.2783, 0.5485, 0.4384, 0.2505, 0.8862],
          [0.5356, 0.6941, 0.2471, 0.2529, 0.7975],
          [0.3907, 0.3535, 0.4585, 0.8398, 0.2933],
          [0.1150, 0.9948, 0.5880, 0.9697, 0.3960]],

         [[0.7182, 0.9535, 0.4175, 0.9015, 0.2996],
          [0.5104, 0.1594, 0.1868, 0.4881, 0.6767],
          [0.6299, 0.2469, 0.6296, 0.9812, 0.3533],
  

In [25]:
#pytorch and numpy

In [27]:
import numpy as np

In [28]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor 

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [31]:
torch.arange(1.0,8.0).dtype

torch.float32