In [1]:
import torch 

In [2]:
torch.cuda.is_available()

True

In [3]:
device = torch.device("cuda")

In [4]:
device 

device(type='cuda')

In [5]:
torch.__version__

'2.5.1'

In [6]:
!nvidia-smi

Wed Dec 24 12:59:53 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.99                 Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   44C    P8              4W /   30W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [7]:
#scalars

scalar = torch.tensor(7)
print(scalar)
print(scalar.item())
print(scalar.ndim)

tensor(7)
7
0


In [8]:
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [9]:
matrix = torch.tensor([[7, 8],
                      [9, 10]])

print(matrix.ndim)
print(matrix[1])
print(matrix.shape)
print(matrix[0: 1])

2
tensor([ 9, 10])
torch.Size([2, 2])
tensor([[7, 8]])


In [10]:
tensor = torch.tensor([[[7, 8, 9],
                        [3,4,5],
                       [10, 11, 13]]])


print(tensor.ndim)
print(tensor.shape)
print(tensor[0: 1])
print(tensor[0:-1])

3
torch.Size([1, 3, 3])
tensor([[[ 7,  8,  9],
         [ 3,  4,  5],
         [10, 11, 13]]])
tensor([], size=(0, 3, 3), dtype=torch.int64)


In [11]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3441, 0.7992, 0.6454, 0.8779],
        [0.2949, 0.9147, 0.6553, 0.1572],
        [0.7218, 0.4151, 0.9566, 0.5727]])

In [12]:
random_image_size_tensor = torch.rand(size=(244, 244, 3)) #height width color channel

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

In [13]:
#default data type is always float32
random_image_size_tensor.dtype

torch.float32

In [14]:
torch.arange(0,10)
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [15]:
torch.rand(1,3) #rows x columns

tensor([[0.6563, 0.7219, 0.4735]])

In [17]:
x = torch.arange(1,10).reshape(1, 3, 3)

x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [18]:
x[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [20]:
x[0][0]

tensor([1, 2, 3])

In [21]:
x[0][0][0]

tensor(1)

In [22]:
#getting all values of 0th and 1st dimension but only index of 1 of 2nd dimension

In [23]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [26]:
x[:, 1, 1]

tensor([5])

In [41]:
torch.rand(2,3,4,5)

tensor([[[[0.6711, 0.4460, 0.5193, 0.1120, 0.0801],
          [0.1287, 0.9800, 0.8226, 0.5208, 0.6981],
          [0.4762, 0.5751, 0.8063, 0.7389, 0.8654],
          [0.4192, 0.3566, 0.2773, 0.0831, 0.0044]],

         [[0.3670, 0.5187, 0.8662, 0.2542, 0.4796],
          [0.6628, 0.8060, 0.1504, 0.8437, 0.2659],
          [0.4317, 0.9026, 0.0400, 0.4232, 0.0436],
          [0.7560, 0.4776, 0.2590, 0.7795, 0.4962]],

         [[0.5017, 0.5419, 0.8731, 0.3514, 0.4359],
          [0.8189, 0.8109, 0.3319, 0.4094, 0.5457],
          [0.6965, 0.8631, 0.3686, 0.6526, 0.4761],
          [0.8898, 0.8304, 0.5930, 0.9563, 0.4877]]],


        [[[0.5395, 0.6854, 0.0710, 0.7113, 0.7458],
          [0.5807, 0.4572, 0.4964, 0.9546, 0.6428],
          [0.0294, 0.0144, 0.8677, 0.4430, 0.5946],
          [0.2070, 0.3491, 0.4351, 0.6852, 0.5572]],

         [[0.2684, 0.8716, 0.1184, 0.0362, 0.7592],
          [0.0155, 0.5842, 0.3038, 0.7729, 0.6746],
          [0.2628, 0.2243, 0.3206, 0.7709, 0.7103],
  