In [ ]:
import torch 

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device("cuda")

In [ ]:
device 

device(type='cuda')

In [ ]:
torch.__version__

'2.5.1'

In [ ]:
!nvidia-smi

Thu Aug 28 11:07:44 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.99                 Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   43C    P3              7W /   30W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
#scalars

scalar = torch.tensor(7)
print(scalar)
print(scalar.item())
print(scalar.ndim)

tensor(7)
7
0


In [ ]:
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [ ]:
matrix = torch.tensor([[7, 8],
                      [9, 10]])

print(matrix.ndim)
print(matrix[1])
print(matrix.shape)
print(matrix[0: 1])

2
tensor([ 9, 10])
torch.Size([2, 2])
tensor([[7, 8]])


In [ ]:
tensor = torch.tensor([[[7, 8, 9],
                        [3,4,5],
                       [10, 11, 13]]])


print(tensor.ndim)
print(tensor.shape)
print(tensor[0: 1])
print(tensor[0:-1])

3
torch.Size([1, 3, 3])
tensor([[[ 7,  8,  9],
         [ 3,  4,  5],
         [10, 11, 13]]])
tensor([], size=(0, 3, 3), dtype=torch.int64)


In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

NameError: name 'torch' is not defined