In [1]:
import torch 

In [2]:
torch.cuda.is_available()

True

In [3]:
device = torch.device("cuda")

In [4]:
device 

device(type='cuda')

In [5]:
torch.__version__

'2.5.1'

In [6]:
!nvidia-smi

Fri Nov 28 14:25:48 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.99                 Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   38C    P3              7W /   30W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [7]:
#scalars

scalar = torch.tensor(7)
print(scalar)
print(scalar.item())
print(scalar.ndim)

tensor(7)
7
0


In [8]:
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [9]:
matrix = torch.tensor([[7, 8],
                      [9, 10]])

print(matrix.ndim)
print(matrix[1])
print(matrix.shape)
print(matrix[0: 1])

2
tensor([ 9, 10])
torch.Size([2, 2])
tensor([[7, 8]])


In [10]:
tensor = torch.tensor([[[7, 8, 9],
                        [3,4,5],
                       [10, 11, 13]]])


print(tensor.ndim)
print(tensor.shape)
print(tensor[0: 1])
print(tensor[0:-1])

3
torch.Size([1, 3, 3])
tensor([[[ 7,  8,  9],
         [ 3,  4,  5],
         [10, 11, 13]]])
tensor([], size=(0, 3, 3), dtype=torch.int64)


In [11]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5177, 0.6059, 0.5733, 0.2728],
        [0.5931, 0.7122, 0.0092, 0.5495],
        [0.9309, 0.0654, 0.0474, 0.8508]])

In [13]:
random_image_size_tensor = torch.rand(size=(244, 244, 3)) #height width color channel

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

In [14]:
#default data type is always float32
random_image_size_tensor.dtype

torch.float32

In [21]:
torch.arange(0,10)
one_to_ten = torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])